### ISSUE TITLE
README.md 404 for lab url

### ISSUE THREAD

**Issue by polarathene** [Adapton/adapton.rust#1]
> Quickstart: See [Adapton Lab](https://github.com/Adapton/adapton-lab.rust)
> More info: Adapton Lab

**Comment by matthewhammer** [comment]
Thanks for the note!

Adapton Lab has become somewhat stale, and ["Fungi Lang"](https://github.com/Adapton/fungi-lang.rust) is in the process of superseding/replacing it's role in the Adapton project.

Until Fungi Lang is ready for users (beyond its current developers), I'll update the README.  For now, I'm just dropping the dead link.
